### ISSUE TITLE
Melhorar implementação de colisão de objetos

### ISSUE THREAD

**Issue by GoliasVictor** [GoliasVictor/jogo.#9]
Melhorar implementação de colisão de objetos, da atual forma seria exaustivo implementar colisões mais complexas, ou com tipos variados. 
É preciso criar colisão pensando em:
- Uma entidade pode começar podendo colidir e no futuro não poder mais e o contrario
- Uma entidade pode ser que ela crie uma alteração em outra entidade.(um botão que abre uma porta)
- Uma entidade precisa saber se ela colidiu com outra entidade ou outra entidade colidiu nela. 
- Uma entidade pode querer desaparecer quando outra entidade colide nela.

**Comment by grandeisa** [comment]
### Sugestão

Como o jogo depende de uma grid onde é possível encontrar um objeto por sua posição, talvez seja interessante que não haja uma implementação genérica de colisão, mas sim que o objeto que precisar lidar com a colisão a faça da forma que achar melhor.

### Exemplo

Em um jogo estou trabalhando, criei uma classe para objetos da grade titulada ```GridEntity```, o player é _child_ deste objeto.

Antes de se mover, o jogador verifica o que está na célula desejada ao chamar a função ```GridEntity? Scene.GetEntityInGrid(int x, int y)``` e lida com o objeto baseado em seu tipo. 

> Se for item, coleta o item e vai para a posição desejada
> Se for inimigo, Game Over
> Se a célula estiver vazia, vai para a posição desejada

___

Como o jogo possui poucos elementos, e a maior parte deles apenas deve interação ao player, talvez valha a pena levar isso em consideração.

**Comment by GoliasVictor** [comment]
É basicamente assim que ta funcionando agora, porém tem alguns detallhes a mais, que é que pode ficar mais de uma entidade em uma posição(por exemplo, um item no chão eu chuto), ai, o que existe é que o PlayerMovimentSystem faz é:
- roda por todos objetos na posição, avisando que o player colidiu com aquele objeto
- verifica se o player pode ficar encima de todos os objetos naquela posição , se não retorna sem fazer nada
- se pode sobrepor, ele move o player pra nova posição
https://github.com/GoliasVictor/jogo./blob/32ca8ab6a64e29f0fa0f6c96376560c313ce3bbd/src/Jogo/Systems/PlayerMovementSystem.cs#L32-L37

O problema da forma atual, é que o colidir pode mover entidades, e essas entidades acabam tendo que fazer um codigo muito parecido com o que o jogador  faz, ai precisaria dar uma melhorada nisso.

**Comment by grandeisa** [comment]
@GoliasVictor 
Existe algum bloco que possa se sobrepor com outro?
